/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controladordebasededatos;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.util.ArrayList;

/**
 *
 * @author Ferchitoo
 */
public class BasedeDatosPersona extends javax.swing.JFrame {

    /**
     * Creates new form BasedeDatosPersona
     */
    Connection connection;
    PreparedStatement seleccionarPersonas;
    PreparedStatement seleccionarPersonasPorApellido;
    PreparedStatement insertarNuevaPersona;
    ArrayList<Persona> listaPersonas;
    Persona persona;
    int i = 0;

    public BasedeDatosPersona() {
        initComponents();
        listaPersonas = new ArrayList();

        this.setLocationRelativeTo(null);
        getConnection();

        txtprevious.setEditable(false);
        txtnext.setEditable(false);

        listaPersonas = getPersona();

        if (listaPersonas.size() > 0) {
            txtAddress_id.setText("" + listaPersonas.get(0).getId());
            txtFirstName.setText(listaPersonas.get(0).getNombres());
            txtLastName.setText(listaPersonas.get(0).getApellido());
            txtEmail.setText(listaPersonas.get(0).getEmail());
            txtPhoneNumber.setText(listaPersonas.get(0).getTelefono());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtAddress_id = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtResultadoBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnMostrarTodo = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        txtprevious = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnext = new javax.swing.JTextField();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AddressBook");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Address_ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 79, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("FirstName");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 123, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("LastName");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 167, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 205, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Phone Number");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 252, -1, -1));
        getContentPane().add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 115, 230, 30));

        txtAddress_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddress_idActionPerformed(evt);
            }
        });
        getContentPane().add(txtAddress_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 230, 30));
        getContentPane().add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 230, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Last Name");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscar.setText("Find");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(34, 34, 34)
                .addComponent(txtResultadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtResultadoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 450, 120));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 230, 30));
        getContentPane().add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 243, 230, 26));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Find an estry by last name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 230, -1));

        btnPrevious.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 30));

        btnMostrarTodo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnMostrarTodo.setText("Browse All Entries");
        btnMostrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        btnInsertar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnInsertar.setText("Insert new Entry");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        txtprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpreviousActionPerformed(evt);
            }
        });
        getContentPane().add(txtprevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 30, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("of");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 20, -1));
        getContentPane().add(txtnext, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 30, 30));

        btnNext.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpreviousActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed

        agregarPersona(Integer.parseInt(txtAddress_id.getText()), txtFirstName.getText(), txtLastName.getText(), txtEmail.getText(), txtPhoneNumber.getText());

    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        getConnection();
        getPersonaApellido(txtResultadoBusqueda.getText());

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtAddress_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddress_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddress_idActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        btnPrevious.setEnabled(true);
        if (i == 0) {
            btnPrevious.setEnabled(false);
        } else {
            i--;
            txtprevious.setText("" + (i + 1));
            txtnext.setText("" + listaPersonas.size());
            txtAddress_id.setText("" + listaPersonas.get(i).getId());
            txtFirstName.setText(listaPersonas.get(i).getNombres());
            txtLastName.setText(listaPersonas.get(i).getApellido());
            txtEmail.setText(listaPersonas.get(i).getEmail());
            txtPhoneNumber.setText(listaPersonas.get(i).getTelefono());
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        btnPrevious.setEnabled(true);
        if (i == listaPersonas.size() - 1) {
            btnNext.setEnabled(false);
        } else {
            i++;
            txtprevious.setText("" + (i + 1));
            txtnext.setText("" + listaPersonas.size());

            txtAddress_id.setText("" + listaPersonas.get(i).getId());
            txtFirstName.setText(listaPersonas.get(i).getNombres());
            txtLastName.setText(listaPersonas.get(i).getApellido());
            txtEmail.setText(listaPersonas.get(i).getEmail());
            txtPhoneNumber.setText(listaPersonas.get(i).getTelefono());
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnMostrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTodoActionPerformed
        for (int j = 0; j < listaPersonas.size(); j++) {
            txtprevious.setText("" + (j + 1));
            txtnext.setText("" + listaPersonas.size());
            txtAddress_id.setText("" + listaPersonas.get(j).getId());
            txtFirstName.setText(listaPersonas.get(j).getNombres());
            txtLastName.setText(listaPersonas.get(j).getApellido());
            txtEmail.setText(listaPersonas.get(j).getEmail());
            txtPhoneNumber.setText(listaPersonas.get(j).getTelefono());
        }
    }//GEN-LAST:event_btnMostrarTodoActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasedeDatosPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasedeDatosPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasedeDatosPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasedeDatosPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasedeDatosPersona().setVisible(true);
            }
        });
    }
        

    public Connection getConnection(){
        try {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
        try {
            connection = DriverManager.getConnection("jdbc:derby://localhost:1527/PersonaDB", "administrador", "admin20");
        } catch (SQLException e) {
            e.printStackTrace();
        }
        
        
        return connection;
    }

    public ArrayList<Persona> getPersona() {
        try {
            String datoSQL = "select * from Persona";
            seleccionarPersonas = connection.prepareStatement(datoSQL);
            ResultSet r = seleccionarPersonas.executeQuery();
            while (r.next()) {
                int id = r.getInt(1);
                String nombres = r.getString(2);
                String apellido = r.getString(3);
                String email = r.getString(4);
                String telefono = r.getString(5);
                Persona p = new Persona(id, nombres, apellido, email, telefono);
                listaPersonas.add(p);
            }
            r.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return listaPersonas;
    }

    public ArrayList<Persona> getPersonaApellido(String apellido) {
        try {
            String datoSQL = "select * from Persona where apellido like '%" + apellido + "%'";
            seleccionarPersonasPorApellido = connection.prepareStatement(datoSQL);
            ResultSet r = seleccionarPersonasPorApellido.executeQuery();
            while (r.next()) {
                txtAddress_id.setText(r.getString(1));
                txtFirstName.setText(r.getString(2));
                txtLastName.setText(r.getString(3));
                txtEmail.setText(r.getString(4));
                txtPhoneNumber.setText(r.getString(5));
            }
            r.close();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return listaPersonas;
    }

    public void agregarPersona(int id, String nombre, String apellido, String email, String telefono) {
        getConnection();
        try {
            String datoSQL = "INSERT INTO PERSONA (ID,NOMBRES,APELLIDO,EMAIL,TELEFONO) values(?,?,?,?,?)";
            insertarNuevaPersona = connection.prepareStatement(datoSQL);
            insertarNuevaPersona.setInt(1, id);
            insertarNuevaPersona.setString(2, nombre);
            insertarNuevaPersona.setString(3, apellido);
            insertarNuevaPersona.setString(4, email);
            insertarNuevaPersona.setString(5, telefono);
            insertarNuevaPersona.executeUpdate();
            connection.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
        System.out.println("Se agrego nueva persona");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnMostrarTodo;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAddress_id;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtResultadoBusqueda;
    private javax.swing.JTextField txtnext;
    private javax.swing.JTextField txtprevious;
    // End of variables declaration//GEN-END:variables
}
